### ISSUE TITLE
[Questions] Can this mod really cause me to get banned? If so why? 

### ISSUE THREAD

**Issue by CatsArmy** [DiFFoZ/LimbusCompanyFixCacheError#1]
I've looked at the code and i cant really see why this would get me banned.

**Comment by DiFFoZ** [comment]
Because game is online, so it can check for loaded assemblies and detect any modification as cheating.

Plus Project Moon (devs of LC) made a note that modding the game will probably can ban your account.

**Comment by CatsArmy** [comment]
So this is a steam thing right like VAC was it I believe right?
